parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: module

plugins:
  - "@typescript-eslint"
  - prettier
  - import
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - "*.config.js"
  - dist
rules:
  prettier/prettier: error
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
  no-control-regex: "off"
  import/order: warn
  import/named: off
