version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  app:
    image: "ghcr.io/sevenc-nanashi/kikoune:latest"
    ports:
      - "$FINAL_PORT:1104"
    env_file: ".env"
